export const FETCH_PROPERTIES_LOADING = 'FETCH_PROPERTIES_LOADING'
export const FETCH_PROPERTIES_SUCCESS = 'FETCH_PROPERTIES_SUCCESS'
export const FETCH_PROPERTIES_ERROR = 'FETCH_PROPERTIES_ERROR'

export const FETCH_MEETINGS_LOADING = 'FETCH_MEETINGS_LOADING'
export const FETCH_MEETINGS_SUCCESS = 'FETCH_MEETINGS_SUCCESS'
export const FETCH_MEETINGS_ERROR = 'FETCH_MEETINGS_ERROR'
export const APPEND_MEETING = 'APPEND_MEETING'

export const SELECT_MEETING = 'SELECT_MEETING'

export const FETCH_MEETING_LOADING = 'FETCH_MEETING_LOADING'
export const FETCH_MEETING_SUCCESS = 'FETCH_MEETING_SUCCESS'
export const FETCH_MEETING_ERROR = 'FETCH_MEETING_ERROR'

export const SET_SUPPORTED = 'SET_SUPPORTED'
export const SET_AGAINST = 'SET_AGAINST'
export const SET_REFRAINED = 'SET_REFRAINED'