export const FETCH_APARTMENTS_LOADING = 'FETCH_APARTMENTS_LOADING'
export const FETCH_APARTMENTS_SUCCESS = 'FETCH_APARTMENTS_SUCCESS'
export const FETCH_APARTMENTS_ERROR = 'FETCH_APARTMENTS_ERROR'

export const FETCH_MEETINGS_LOADING = 'FETCH_MEETINGS_LOADING'
export const FETCH_MEETINGS_SUCCESS = 'FETCH_MEETINGS_SUCCESS'
export const FETCH_MEETINGS_ERROR = 'FETCH_MEETINGS_ERROR'
export const APPEND_MEETING = 'APPEND_MEETING'

export const SELECT_MEETING = 'SELECT_MEETING'